FROM node:22-alpine
LABEL org.opencontainers.image.source=https://github.com/OleksiuDatsko/news

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 5173

CMD ["yarn", "run", "dev", "--host"]