FROM python:3.13-slim

RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY crontab /etc/cron.d/daily-digest-cron

RUN chmod 0644 /etc/cron.d/daily-digest-cron

RUN crontab /etc/cron.d/daily-digest-cron

RUN touch /var/log/cron.log

COPY . .

CMD sh -c "cron && tail -f /var/log/cron.log"