@startuml UseCase
left to right direction

actor "Гість" as Guest
actor "Користувач" as User
actor "Адміністратор" as Admin
actor "Система" as System

Guest <|-- User
User <|-- Admin

package "Головний сайт" {
    Guest -- (Перегляд статей)
    Guest -- (Перегляд категорій)
    Guest -- (Перегляд авторів)
    Guest -- (Пошук статей)

    (Перегляд статей) ..> (Отримання реклами) : <<include>>
}

package "Профіль користувача" {
    User -- (Автентифікація)
    User -- (Керування профілем)
    User -- (Взаємодія зі статтями)
    User -- (Керування підписками)
    User -- (Слідкування за авторами)
    User -- (Керування сповіщеннями)

    (Автентифікація) <.. (Вхід та Вихід): <<extend>>
    (Автентифікація) <.. (Реєстрація)   : <<extend>>

    (Взаємодія зі статтями) ..> (Коментування) : <<include>>
    (Взаємодія зі статтями) ..> (Оцінка лайк) : <<include>>
    (Взаємодія зі статтями) ..> (Збереження статей) : <<include>>

    (Керування сповіщеннями) ..> (Підписка на Push) : <<include>>
    (Керування сповіщеннями) ..> (Підписка на Email) : <<include>>

    (Керування профілем) ..> (Налаштування тем) : <<include>>
   
}

package "Адмін-панель" {
    Admin -- (Керування контентом)
    Admin -- (Керування користувачами)
    Admin -- (Керування монетизацією)
    Admin -- (Керування адміністраторами)

    (Керування контентом) ..> (CRUD Статті) : <<include>>
    (Керування контентом) ..> (CRUD Автори) : <<include>>
    (Керування контентом) ..> (CRUD Категорії) : <<include>>

    (Керування монетизацією) ..> (CRUD Реклама) : <<include>>
    (Керування монетизацією) ..> (CRUD Плани підписок) : <<include>>

    (Керування користувачами) <.. (Зміна підписки користувача) : <<extend>>
}

package "Системні задачі" {
    System -- (Надсилання дайджестів)
    (Надсилання дайджестів) ..> (Надсилання Push) : <<include>>
    (Надсилання дайджестів) ..> (Надсилання Email stub) : <<include>>
}

@enduml
