"""empty message

Revision ID: 21330fa0c40a
Revises: 89c16e458321
Create Date: 2025-09-27 21:01:06.794505

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21330fa0c40a"
down_revision = "89c16e458321"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
