"""empty message

Revision ID: 6b12ee39fde5
Revises: 505142bd11fd
Create Date: 2025-11-03 11:10:31.453916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b12ee39fde5'
down_revision = '505142bd11fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.Text(), nullable=False))
        batch_op.create_unique_constraint('uq_categories_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_categories_slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
